services:
    atlas-frontend:
        build:
            target: dev
            context: ./
        volumes:
            - ./:/frontend
            - /frontend/node_modules
        ports:
            - 8080:8080